let index

const Succès = document.getElementById('Succès');
let tab_Succès = [
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney",
    "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
    "Le seul endroit où le succès vient avant le travail, c’est dans le dictionnaire. – Vidal Sassoon",
    "La réussite, c’est tomber sept fois et se relever huit. – Proverbe japonais",
    "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
    "Il n’y a qu’une seule réussite : arriver à vivre sa vie à sa façon. – Christopher Morley",
    "La persévérance est le secret de toutes les victoires. – Victor Hugo",
    "Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme. – Winston Churchill",
    "L’échec est simplement l’opportunité de recommencer, cette fois plus intelligemment. – Henry Ford",
    "Le futur dépend de ce que vous faites aujourd’hui. – Gandhi",
    "Si vous pouvez le rêver, vous pouvez le faire. – Walt Disney"
];

const liens_categorie = document.getElementById('liens_categorie');
function addCaté(n) {
    // si n est un id
    citations.textContent = ''
    let elem = document.getElementById(n);
    if (elem) {
        // Récupère le texte du bouton ou du lien cliqué
        liens_categorie.textContent = elem.textContent;
        console.log(elem);

    } else {
        console.warn("Aucun élément trouvé avec l'id :", n);
    }
    générer.addEventListener("click", function () {
        if (liens_categorie.textContent === '🏆Succès') {

            index = Math.floor(Math.random() * tab_Succès.length);
            citations.textContent = tab_Succès[index];
            console.log(index)
        }
    });
}

